In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
google = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\google_stock_price.csv", squeeze = True)

In [4]:
google.head()

0    50.12
1    54.10
2    54.65
3    52.38
4    52.95
Name: Stock Price, dtype: float64

In [6]:
google.loc[4]

52.95

In [7]:
google.iloc[4]

52.95

In [10]:
s = pd.Series(np.arange(23))
s > 10

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
dtype: bool

In [15]:
s1 = pd.Series(np.random.randn(3))
s2 = pd.Series(np.random.randn(3))
combined = pd.concat([s1, s2])
combined

0    0.721555
1   -0.706771
2   -1.039575
0    0.271860
1   -0.424972
2    0.567020
dtype: float64

In [18]:
s1.reindex(["c", "b" ,"a","c", "b" ,"a"])

c   NaN
b   NaN
a   NaN
c   NaN
b   NaN
a   NaN
dtype: float64

In [19]:
google.head()

0    50.12
1    54.10
2    54.65
3    52.38
4    52.95
Name: Stock Price, dtype: float64

In [20]:
del(google[0])

In [21]:
google.head()

1    54.10
2    54.65
3    52.38
4    52.95
5    53.90
Name: Stock Price, dtype: float64

# The pandas DataFrame Object

A DataFrame object can be thought of as a dictionary-like container of one or more
Series objects, or as a spreadsheet, probably the best description for those new to
pandas is to compare a DataFrame object to a relational database table. However,
even that comparison is limited, as a DataFrame object has very distinct qualities
(such as automatic data alignment of series) that make it much more capable for
__exploratory data analysis__ than either a spreadsheet or relational database table.

In [35]:
df = pd.DataFrame(np.arange(25).reshape(5,5), columns=["a", "b", "c", "d", "e"])

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [38]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
df.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
s3 = pd.Series(np.arange(12,14), index=[1, 2])

In [42]:
df = pd.DataFrame({"c1" : s3 , "c2" : s3 ,"c3" : s3})

In [43]:
df

   c1  c2  c3
1  12  12  12
2  13  13  13

In [46]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv")

In [47]:
basketball

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
kashmir = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\kashmir.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (15,71,88) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [49]:
kashmir

,user_id,status_id,created_at,screen_name,text,source,display_text_width,reply_to_status_id,reply_to_user_id,reply_to_screen_name,...,favourites_count,account_created_at,verified,profile_url,profile_expanded_url,account_lang,profile_banner_url,profile_background_url,profile_image_url,country_name
0,x2852249323,x1074094115938279424,16-12-18 0:09,AliasWardak,The size of #India is a factor but I believe t...,Twitter for iPhone,200,NaN,NaN,NaN,...,634,11-10-14 17:12,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/28522493...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/8522268400...,Afghanistan
1,x2852249323,x1074091482934636544,15-12-18 23:58,AliasWardak,@zeeshan_shah_dc @zeeshan_shah_dc I believe th...,Twitter for iPhone,177,x836659355672006660,x593342422,zeeshan_shah_dc,...,634,11-10-14 17:12,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/28522493...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/8522268400...,Afghanistan
2,x168259012,x1074614642163499011,17-12-18 10:37,TOLOnews,"Indian Forces Lock Down #Kashmir City, Hold Le...",Twitter Web Client,94,NaN,NaN,NaN,...,57,18-07-10 21:24,True,http://t.co/1gn3hdHtIy,http://TOLOnews.com,en,https://pbs.twimg.com/profile_banners/16825901...,http://abs.twimg.com/images/themes/theme14/bg.gif,http://pbs.twimg.com/profile_images/6313856570...,Afghanistan
3,x40407930,x1073917367602814976,15-12-18 12:27,HuriaSamira,Reading about #Kashmir from two dear friends. ...,Twitter for iPhone,112,NaN,NaN,NaN,...,5846,16-05-09 4:18,True,https://t.co/DJL0CxRiUS,https://m.facebook.com/WKLOA/,en,https://pbs.twimg.com/profile_banners/40407930...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1074166662...,Afghanistan
4,x598779224,x1073648251369271296,14-12-18 18:37,Fabriortiz04,Game day <U+26BD><U+FE0F><U+0001F4AA><U+0001F3...,Twitter for iPhone,245,NaN,NaN,NaN,...,3007,04-06-12 0:21,False,https://t.co/Cb05OPOpjU,https://m.youtube.com/channel/UCZkbsrwBCcq_Lf2...,es,https://pbs.twimg.com/profile_banners/59877922...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1012096930...,Argentina
5,x254541171,x1074624961246085120,17-12-18 11:18,NEWSam_English,#Indian armed forces isolate #Kashmir to preve...,Twitter Web Client,81,NaN,NaN,NaN,...,47,19-02-11 13:55,False,http://t.co/EF6z3EX1uu,http://news.am/eng,en,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1248925618...,Armenia
6,x97128369,x1075583030041882624,20-12-18 2:45,Coppagee,Pic of the Day:\r\nHouseboats\r\nLake Dal\r\nK...,Twitter Web Client,275,NaN,NaN,NaN,...,5748,16-12-09 3:48,False,https://t.co/698lcYrHLG,http://www.christinehillingdon.com,en,https://pbs.twimg.com/profile_banners/97128369...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/8201204479...,Australia
7,x97128369,x1075222328076685313,19-12-18 2:52,Coppagee,"Pic of the Day:\r\nLake Dal, Srinagar,\r\nKash...",Twitter Web Client,247,NaN,NaN,NaN,...,5748,16-12-09 3:48,False,https://t.co/698lcYrHLG,http://www.christinehillingdon.com,en,https://pbs.twimg.com/profile_banners/97128369...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/8201204479...,Australia
8,x1014042087501660160,x1075607687973429252,20-12-18 4:23,ForLovenFreedom,@cjwerleman Hey @MitchJohnson398 check this ou...,Twitter for Android,284,x1075480544039718914,x33519870,cjwerleman,...,2005,03-07-18 7:04,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10140420...,NaN,http://pbs.twimg.com/profile_images/1014408229...,Australia
9,x577792575,x1076004160036687872,21-12-18 6:39,wired_we,@YangheeLeeSKKU &amp; PA again <U+0001F642>\r\...,Twitter Web Client,288,x1076002109571489793,x577792575,wired_we,...,1743,12-05-12 3:58,False,NaN,NaN,en,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/9791541591...,Australia
10,x865629578852577280,x1074685413074354176,17-12-18 15:19,Kashmir2k19,Pulwama Killings Aftermath\r\n\r\nAs precautio...,Twitter Web Client,235,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
11,x865629578852577280,x1076352661174276096,22-12-18 5:44,Kashmir2k19,#FLASH\r\n\r\n#Kashmir: Hi- Speed Internet (3G...,Twitter Web Client,100,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
12,x865629578852577280,x1074681255936036864,17-12-18 15:02,Kashmir2k19,#Flash\r\n\r\nClass work to remain suspended i...,Twitter Web Client,107,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
13,x865629578852577280,x1076369395230871552,22-12-18 6:50,Kashmir2k19,Out of these 9 #AnsarGazwatulHind mujahideen ...,Twitter Web Client,106,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
14,x865629578852577280,x1076341323807051776,22-12-18 4:59,Kashmir2k19,"6 Armed Liberation Fighters Martyred ,Among th...",Twitter Web Client,157,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
15,x865629578852577280,x1074685927744774145,17-12-18 15:21,Kashmir2k19,Pulwama killings: Offer Giabana Nimaaz Jinazah...,Twitter Web Client,90,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
16,x865629578852577280,x1076340644468215809,22-12-18 4:56,Kashmir2k19,Six Armed Liberation Fighters Martyred in So...,Twitter Web Client,105,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
17,x865629578852577280,x1076353749105426442,22-12-18 5:48,Kashmir2k19,Fallen AGH men in Tral\r\n\r\n- Rehan Khan (Tr...,Twitter Web Client,280,NaN,NaN,NaN,...,140,19-05-17 18:05,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1057302853...,Australia
18,x1019563982,x1075264940431204352,19-12-18 5:41,JasumatiPatel,@Demise____ @rajsubhasish @AdityaRajKaul @Ragh...,Twitter for iPad,266,x1075062021530382336,x518003346,Demise____,...,35120,18-12-12 11:24,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10195639...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1054316791...,Australia
19,x1019563982,x1075264658699735040,19-12-18 5:40,JasumatiPatel,This Aussie idiot never been to #Kashmir. Mout...,Twitter for iPad,265,NaN,NaN,NaN,...,35120,18-12-12 11:24,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10195639...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1054316791...,Australia
20,x959956292767965184,x1074051060149309441,15-12-18 21:18,NaumanNiamat,@ImaanZHazir A pseudo liberal's life got compl...,Twitter for Android,271,x1073277392712548353,x362746534,ImaanZHazir,...,4181,04-02-18 1:06,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/95995629...,NaN,http://pbs.twimg.com/profile_images/1062878241...,Australia
21,x518003346,x1075940039446519808,21-12-18 2:24,Demise____,@jasmineDm101 account has been suspended.@Twit...,Twitter for iPad,263,NaN,x4801953853,jasmineDm101,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
22,x518003346,x1073829705231433728,15-12-18 6:38,Demise____,@SuddhanSadaf @UNHumanRights @hrw @amnesty @UN...,Twitter for iPad,118,x1073821893013241856,x1020237020000542720,SuddhanSadaf,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
23,x518003346,x1075929691813339136,21-12-18 1:43,Demise____,@jasmineDm101 @Twitter It’s sad ppl who indulg...,Twitter for iPad,195,x1075926282389475328,x4801953853,jasmineDm101,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
24,x518003346,x1073085086457769984,13-12-18 5:19,Demise____,@YasinhamzaYasin @adgpi Yasin I read ur timeli...,Twitter for iPad,272,x1073080722469068802,x764511517433798658,YasinhamzaYasin,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
25,x518003346,x1076415636006305792,22-12-18 9:54,Demise____,@vipulkapoor1605 @MadihaShakil And you are a #...,Twitter for iPad,149,x1076403389578297345,x1095295038,vipulkapoor1605,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
26,x518003346,x1075911938310193153,21-12-18 0:32,Demise____,@abumusfira333 @HanaAshtar1 Brother in Islam y...,Twitter for iPad,127,x1075808259481554944,x900360627289333760,abumusfira333,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
27,x518003346,x1075813568468013056,20-12-18 18:01,Demise____,@AnarKaDana @KashmirCause_ We are alive to mak...,Twitter for iPad,100,x1075798975586828288,x854900767206985730,AnarKaDana,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
28,x518003346,x1076527813430136832,22-12-18 17:20,Demise____,@abumusfira333 Brother in Islam 6 militants go...,Twitter for iPad,125,x1076521968512335872,x900360627289333760,abumusfira333,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
29,x518003346,x1073818499976388609,15-12-18 5:54,Demise____,Second Civilian Killed As Forces Open Fire Upo...,Twitter for iPad,275,NaN,NaN,NaN,...,11683,07-03-12 22:48,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/51800334...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1064881661...,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9183,x412019402,x1073481108686172160,14-12-18 7:33,kevinpoonjar,@MirwaizKashmir Instead of doing photo ops to ...,Twitter for Android,274,x1072804019666632704,x2489431314,MirwaizKashmir,...,1979,14-11-11 5:09,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/41201940...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1069152677...,NaN
9184,x116403691,x1073395836971876353,14-12-18 1:54,AwesomeIqbal,And here some pseudo intellectuals believe BBC...,Twitter for Android,121,NaN,NaN,NaN,...,197,22-02-10 9:46,False,NaN,NaN,en,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/2283022013...,NaN
9185,x1047583943313281024,x1073288796039311360,13-12-18 18:49,living_kashmir,Fresh snowfall in #Kashmir. \r\nJust holding '...,Twitter for Android,106,NaN,NaN,NaN,...,59,03-10-18 20:27,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10475839...,NaN,http://pbs.twimg.com/profile_images/1063499285...,NaN
9186,x3233348959,x1073235954343837699,13-12-18 15:19,haroonzia2004,@ipsarkar514 @OfficialDGISPR Are you also prou...,Twitter for Android,61,x1073174389766664192,x3191486800,ipsarkar514,...,2590,02-06-15 7:51,False,NaN,NaN,en,NaN,http://abs.twimg.com/images/themes/theme8/bg.gif,http://pbs.twimg.com/profile_images/1036506566...,NaN
9187,x1034476134820339712,x1073223080170815488,13-12-18 14:28,MajeedBarkat,#Kashmir bleeds# our two more brothers have be...,Twitter for Android,85,NaN,NaN,NaN,...,56,28-08-18 16:21,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10344761...,NaN,http://pbs.twimg.com/profile_images/1074964000...,NaN
9188,x2949111092,x1073122280815812608,13-12-18 7:47,SabahKashmiri,"Barrister Abdul Majeed Tramboo, International ...",Twitter Web Client,223,NaN,NaN,NaN,...,482,29-12-14 4:55,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/29491110...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/7958809789...,NaN
9189,x2949111092,x1073185680824680449,13-12-18 11:59,SabahKashmiri,"Yes, the barbarity must be stopped in #Pakista...",Twitter Web Client,157,NaN,NaN,NaN,...,482,29-12-14 4:55,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/29491110...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/7958809789...,NaN
9190,x2949111092,x1073123389122928640,13-12-18 7:52,SabahKashmiri,The parliament must look into as to who is the...,Twitter Web Client,164,NaN,NaN,NaN,...,482,29-12-14 4:55,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/29491110...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/7958809789...,NaN
9191,x4826969055,x1073182462161944578,13-12-18 11:46,mayra_writes,#India should stop gross #humanrights violatio...,Twitter for iPhone,161,NaN,NaN,NaN,...,978,19-01-16 17:26,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/48269690...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1067125156...,NaN
9192,x743866152548343808,x1073106176252866560,13-12-18 6:43,trivedinaimish1,RESULTS OF #results2018\r\n#ISI SE ZYADA KHOOS...,Twitter Web Client,284,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9193,x743866152548343808,x1073162056289800194,13-12-18 10:25,trivedinaimish1,RESULTS OF #Results2018\r\nGADAAR &amp; #Terro...,Twitter Web Client,286,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9194,x743866152548343808,x1073107083900272641,13-12-18 6:47,trivedinaimish1,RESULTS OF #results2018\r\n#ISI SE ZYADA KHOOS...,Twitter Web Client,284,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9195,x743866152548343808,x1073109094330904576,13-12-18 6:55,trivedinaimish1,RESULTS OF #results2018\r\n#ISI SE ZYADA KHOOS...,Twitter Web Client,284,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9196,x743866152548343808,x1073107866884628480,13-12-18 6:50,trivedinaimish1,RESULTS OF #results2018\r\n#ISI SE ZYADA KHOOS...,Twitter Web Client,284,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9197,x743866152548343808,x1073166751636942848,13-12-18 10:44,trivedinaimish1,#Result2018\r\n#Kashmir BELONGS TO #Pakistan\r...,Twitter Web Client,283,NaN,NaN,NaN,...,190,17-06-16 18:01,False,NaN,NaN,en,NaN,NaN,http://abs.twimg.com/sticky/default_profile_im...,NaN
9198,x2241711865,x1073144948881530880,13-12-18 9:17,IndiaReddit,"""Life imitating art imitating life."" - /u/18La...",Twitter Web Client,263,NaN,NaN,NaN,...,395,12-12-13 3:03,False,http://t.co/XdzMw6noPp,http://indianews.reddit.com,en,NaN,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/4454262558...,NaN
9199,x53614868,x1073132577920290816,13-12-18 8:28,KashmirDespatch,#Post #Sopore #Encounter DIG North #Kashmir At...,Facebook,103,NaN,NaN,NaN,...,187,04-07-09 6:35,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/53614868...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/6077880681...,NaN
9200,x4863469133,x1073130234860527618,13-12-18 8:19,DawnOfFreedom1,A picture of youngest pellet victim of #Kashmi...,Twitter for Android,150,NaN,NaN,NaN,...,311,30-01-16 11:27,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/48634691...,NaN,http://pbs.twimg.com/profile_images/8666052937...,NaN
9201,x1060220946060111872,x1073127708127830017,13-12-18 8:09,KamraNR69413330,#Tehreek_ul_Mujhaideen #kashmir lost 5 armed f...,Twitter Lite,209,NaN,NaN,NaN,...,26,07-11-18 17:22,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1076193811...,NaN
9202,x1048479252033822720,x1073121761972142080,13-12-18 7:45,UBPakistan,Kashmiri actor starring in “Haider” martyred b...,Twitter Web Client,240,NaN,NaN,NaN,...,37,06-10-18 7:45,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10484792...,NaN,http://pbs.twimg.com/profile_images/1048479936...,NaN
9203,x1068525231394836482,x1073097494555353088,13-12-18 6:09,mattj70745685,"So many lives lost, young ones drawn to terror...",Twitter Lite,279,NaN,NaN,NaN,...,285,30-11-18 15:20,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/10685252...,NaN,http://pbs.twimg.com/profile_images/1068526395...,NaN
9204,x911912162964135936,x1073085216959463424,13-12-18 5:20,ShrutiAIR_News,Two terrorist were killed in an overnight #enc...,Twitter for Android,109,NaN,NaN,NaN,...,597,24-09-17 11:16,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/9303675134...,NaN
9205,x905339684888256512,x1073081379246620672,13-12-18 5:05,Mansoor96962014,"@UNHumanRights r U existing anywhere, if yes t...",Twitter for Android,97,NaN,x69231187,UNHumanRights,...,183,06-09-17 7:59,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1046970239...,NaN
9206,x921321598543585280,x1073074280529682432,13-12-18 4:36,NewzalertIn,#Weather Update\r\n\r\nWeather to improve sign...,Twitter for Android,180,NaN,NaN,NaN,...,22,20-10-17 10:26,False,https://t.co/FxnPOPKv9p,https://www.facebook.com/newzalert.co.in/,en,https://pbs.twimg.com/profile_banners/92132159...,NaN,http://pbs.twimg.com/profile_images/9571959999...,NaN
9207,x24567332,x1073071916825657344,13-12-18 4:27,sairmir,"For months now, this handle has been stealing ...",Twitter for Android,135,NaN,NaN,NaN,...,3,15-03-09 19:01,False,https://t.co/WPJvz2lqT4,https://sairmir.wordpress.com/,en,https://pbs.twimg.com/profile_banners/24567332...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/1076151387...,NaN
9208,x1024351275272552448,x1073069662034890752,13-12-18 4:18,AkshitaBahugun1,An encounter broke between security forces and...,Twitter for Android,133,NaN,NaN,NaN,...,26,31-07-18 17:49,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/1044998273...,NaN
9209,x862946835723206656,x1073062851835777024,13-12-18 3:51,md_shoaib32,A man performing ablution (wuzu) for prayer in...,Twitter Web Client,247,NaN,NaN,NaN,...,1494,12-05-17 8:25,False,NaN,NaN,en,NaN,NaN,http://pbs.twimg.com/profile_images/8716230324...,NaN
9210,x770673189894647808,x1073062216981798912,13-12-18 3:49,Guru_Wonder,The martyrdom of Shri. Guru Tegh Bhadur ji\r\n...,Twitter Web Client,235,NaN,NaN,NaN,...,64,30-08-16 17:23,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/77067318...,NaN,http://pbs.twimg.com/profile_images/1057450034...,NaN
9211,x141381979,x1073046399581913088,13-12-18 2:46,deepakgupta1,#Jammu #Kashmir Administrative Services row: C...,Twitter for iPhone,138,NaN,NaN,NaN,...,1597,07-05-10 23:30,False,https://t.co/11fJS71YH8,https://about.me/deepakkgupta,en,https://pbs.twimg.com/profile_banners/14138197...,http://abs.twimg.com/images/themes/theme14/bg.gif,http://pbs.twimg.com/profile_images/1068074294...,NaN
9212,x825081107083300865,x1072943850191241217,12-12-18 19:58,NeedhiMurasu,#Mood_of_the_Nation PICKED from #Facebook :\r\...,Twitter for Android,275,NaN,NaN,NaN,...,1391,27-01-17 20:40,False,NaN,NaN,en,https://pbs.twimg.com/profile_banners/82508110...,NaN,http://pbs.twimg.com/profile_images/8251323712...,NaN

In [50]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [51]:
basketball.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
basketball.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [59]:
basketball.index

RangeIndex(start=0, stop=458, step=1)

In [60]:
basketball.count()

Name        457
Team        457
Number      457
Position    457
Age         457
Height      457
Weight      457
College     373
Salary      446
dtype: int64

In [61]:
basketball.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [62]:
basketball.shape

(458, 9)

In [64]:
basketball.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [65]:
basketball.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [66]:
basketball.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [67]:
basketball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [90]:
revenue = pd.read_csv("D:/python/Data Analysis with Python/#Udemy/Pandas/rev.csv", index_col = "Date")

In [91]:
revenue

         New York  Los Angeles  Miami
Date
1/1/16        985          122    499
1/2/16        738          788    534
1/3/16         14           20    933
1/4/16        730          904    885
1/5/16        114           71    253
1/6/16        936          502    497
1/7/16        123          996    115
1/8/16        935          492    886
1/9/16        846          954    823
1/10/16        54          285    216

In [92]:
a = pd.Series([1, 2, 3])

In [94]:
a.sum()

6

In [98]:
revenue.sum(axis = 0)

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

---------------------------------------------------------------------------

In [103]:
#Selcting a single column
basketball.Name
basketball.Number.head()

0     0.0
1    99.0
2    30.0
3    28.0
4     8.0
Name: Number, dtype: float64

In [118]:
#Bracket syntax - Will work even with columns having spaces
basketball["Name"].head() # A Series if you pass a string

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [119]:
#Selcting a multiple columns
basketball[["Name", "Number", "Salary"]].head(n = 10) # A DataFrame if you pass a string of list

            Name  Number      Salary
0  Avery Bradley     0.0   7730337.0
1    Jae Crowder    99.0   6796117.0
2   John Holland    30.0         NaN
3    R.J. Hunter    28.0   1148640.0
4  Jonas Jerebko     8.0   5000000.0
5   Amir Johnson    90.0  12000000.0
6  Jordan Mickey    55.0   1170960.0
7   Kelly Olynyk    41.0   2165160.0
8   Terry Rozier    12.0   1824360.0
9   Marcus Smart    36.0   3431040.0

In [120]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [124]:
basketball["Name"].head()

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [125]:
basketball[["Name", "Team"]].head()

            Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [128]:
#If the column doesn't exist pandas will create a Universal value/Scalar Value
basketball["Sport"] = "Basketball"

In [129]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball

In [130]:
basketball["League"] = "NBA"

In [132]:
basketball.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball,NBA
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,Basketball,NBA
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,Basketball,NBA
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,Basketball,NBA
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball,NBA

In [147]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv")

In [148]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

__Method__ for inserting a column // much better way

In [149]:
#Method for inserting a column // much better way
basketball.insert(4, column = "Sport", value = "Basketball")

In [150]:
basketball.head()

,Name,Team,Number,Position,Sport,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,Basketball,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,Basketball,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,Basketball,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,Basketball,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,Basketball,29.0,6-10,231.0,NaN,5000000.0

In [151]:
basketball.insert(2, column = "League", value = "NBA")

In [152]:
basketball.head()

,Name,Team,League,Number,Position,Sport,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,NBA,0.0,PG,Basketball,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,NBA,99.0,SF,Basketball,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,NBA,30.0,SG,Basketball,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,NBA,28.0,SG,Basketball,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,NBA,8.0,PF,Basketball,29.0,6-10,231.0,NaN,5000000.0

# Broadcasting Operation (Basic Math Operations applied on all the values)

In [155]:
#Broadcasting Operation
basketball["Age"].add(5)
# .add / .sub / .mul / .div

0    30.0
1    30.0
2    32.0
3    27.0
4    34.0
Name: Age, dtype: float64

In [158]:
basketball["Weight in Kgs"] = basketball["Weight"].mul(0.453592)

In [159]:
basketball.head()

,Name,Team,League,Number,Position,Sport,Age,Height,Weight,College,Salary,Weight in Kgs
0,Avery Bradley,Boston Celtics,NBA,0.0,PG,Basketball,25.0,6-2,180.0,Texas,7730337.0,81.646560
1,Jae Crowder,Boston Celtics,NBA,99.0,SF,Basketball,25.0,6-6,235.0,Marquette,6796117.0,106.594120
2,John Holland,Boston Celtics,NBA,30.0,SG,Basketball,27.0,6-5,205.0,Boston University,NaN,92.986360
3,R.J. Hunter,Boston Celtics,NBA,28.0,SG,Basketball,22.0,6-5,185.0,Georgia State,1148640.0,83.914520
4,Jonas Jerebko,Boston Celtics,NBA,8.0,PF,Basketball,29.0,6-10,231.0,NaN,5000000.0,104.779752

In [161]:
basketball["Salary"].div(1000000).head()

0    7.730337
1    6.796117
2         NaN
3    1.148640
4    5.000000
Name: Salary, dtype: float64

## value_counts() Method

In [166]:
#This works because the DataFrame is returning a Series Object
basketball["Team"].value_counts()

New Orleans Pelicans      19
Memphis Grizzlies         18
Milwaukee Bucks           16
New York Knicks           16
Houston Rockets           15
Toronto Raptors           15
Dallas Mavericks          15
Golden State Warriors     15
Denver Nuggets            15
San Antonio Spurs         15
Boston Celtics            15
Brooklyn Nets             15
Charlotte Hornets         15
Sacramento Kings          15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Los Angeles Lakers        15
Detroit Pistons           15
Indiana Pacers            15
Atlanta Hawks             15
Chicago Bulls             15
Miami Heat                15
Los Angeles Clippers      15
Utah Jazz                 15
Philadelphia 76ers        15
Phoenix Suns              15
Washington Wizards        15
Cleveland Cavaliers       15
Minnesota Timberwolves    14
Orlando Magic             14
Name: Team, dtype: int64

In [ ]:
#basketball[["Team"]].value_counts() will not work

In [169]:
basketball["Height"].value_counts().head(1)

6-9    59
Name: Height, dtype: int64

# DROP ROWS AND NaN VALUES

In [174]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv")

In [177]:
basketball.dropna(how = "all", inplace = True) #all/any

In [182]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [183]:
#removes columns which has NaN 
basketball.dropna(axis = 1).head()

            Name            Team  Number Position   Age Height  Weight
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

In [185]:
#removes row which has NaN to that specific columns in the subset
basketball.dropna(subset = ["Salary", "College"])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

# .fillna() METHOD

In [186]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv")

In [187]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [188]:
basketball.fillna(0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,0,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,0,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,0,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,0,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,0,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,0,0,0.0,0,0.0,0,0.0,0,0.0

In [190]:
basketball["Salary"].fillna(0, inplace = True)

In [191]:
basketball

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [192]:
basketball["College"].fillna("No College", inplace = True)

In [194]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,No College,5000000.0

# .astype() Menthod
converting float64 to int32

In [197]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv").dropna(how = "all")

In [199]:
basketball.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [200]:
basketball["Salary"].fillna(0, inplace = True)

In [201]:
basketball["College"].fillna("No College", inplace = True)

In [202]:
basketball.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,No College,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,No College,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [213]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231.0,No College,5000000

In [204]:
basketball.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [222]:
basketball.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null category
Number      457 non-null int32
Position    457 non-null category
Age         457 non-null int32
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null int32
dtypes: category(2), float64(1), int32(3), object(3)
memory usage: 25.8+ KB

In [207]:
basketball["Salary"] = basketball["Salary"].astype("int") #object ->integer

In [209]:
basketball["Number"] = basketball["Number"].astype("int")

In [211]:
basketball["Age"] = basketball["Age"].astype("int")

In [ ]:
basketball["Number"] = basketball["Number"].astype("int")

In [217]:
#category
basketball["Position"].nunique() #unique and nunique

5

In [219]:
basketball["Position"] = basketball["Position"].astype("category")

In [221]:
basketball["Team"] = basketball["Team"].astype("category")

# Sort a DataFrame with the .sort_values() Method, Part I

In [223]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv").dropna(how = "all")

In [224]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [225]:
basketball.sort_values("Team") #inplace later

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
317,Lamar Patterson,Atlanta Hawks,13.0,SG,24.0,6-5,225.0,Pittsburgh,525093.0
309,Kent Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
313,Kris Humphries,Atlanta Hawks,43.0,PF,31.0,6-9,235.0,Minnesota,1000000.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276.0
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,NaN,1763400.0
319,Mike Scott,Atlanta Hawks,32.0,PF,27.0,6-8,237.0,Virginia,3333333.0
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000.0
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
...,...,...,...,...,...,...,...,...,...
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600.0
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465.0
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960.0
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,NaN,13000000.0
374,JJ Hickson,Washington Wizards,21.0,C,27.0,6-9,242.0,North Carolina State,273038.0
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,NaN,11217391.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
371,Jarell Eddie,Washington Wizards,8.0,SG,24.0,6-7,218.0,Virginia Tech,561716.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950.0
370,Jared Dudley,Washington Wizards,1.0,SF,30.0,6-7,225.0,Boston College,4375000.0

In [228]:
basketball.sort_values("Name")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,NaN,4389607.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
287,Alonzo Gee,New Orleans Pelicans,15.0,SF,29.0,6-6,225.0,Alabama,1320000.0
348,Amar'e Stoudemire,Miami Heat,5.0,PF,33.0,6-10,245.0,NaN,947276.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,NaN,289755.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
362,Andrew Nicholson,Orlando Magic,44.0,PF,26.0,6-9,250.0,St. Bonaventure,2380593.0
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680.0
108,Anthony Brown,Los Angeles Lakers,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730.0
421,Anthony Morrow,Oklahoma City Thunder,2.0,SG,30.0,6-5,210.0,Georgia Tech,3344000.0
195,Anthony Tolliver,Detroit Pistons,43.0,PF,31.0,6-8,240.0,Creighton,3000000.0
...,...,...,...,...,...,...,...,...,...
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
325,Troy Daniels,Charlotte Hornets,30.0,SG,24.0,6-4,205.0,Virginia Commonwealth,947276.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
345,Tyler Johnson,Miami Heat,8.0,SG,24.0,6-4,186.0,Fresno State,845059.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
343,Udonis Haslem,Miami Heat,40.0,PF,36.0,6-8,235.0,Florida,2854940.0
363,Victor Oladipo,Orlando Magic,5.0,SG,24.0,6-4,210.0,Indiana,5192520.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,6-7,215.0,Syracuse,1100602.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
385,Will Barton,Denver Nuggets,5.0,SF,25.0,6-6,175.0,Memphis,3533333.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0

In [229]:
#NaN will be by default placed at the end

# Sort a DataFrame with the .sort_values() Method, Part II

In [231]:
basketball.sort_values(["Team", "Name"], ascending = [True, False])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,NaN,9756250.0
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,NaN,4000000.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
319,Mike Scott,Atlanta Hawks,32.0,PF,27.0,6-8,237.0,Virginia,3333333.0
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276.0
317,Lamar Patterson,Atlanta Hawks,13.0,SG,24.0,6-5,225.0,Pittsburgh,525093.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
313,Kris Humphries,Atlanta Hawks,43.0,PF,31.0,6-9,235.0,Minnesota,1000000.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
309,Kent Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000.0
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,NaN,1763400.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465.0
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,NaN,13000000.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600.0
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,NaN,11217391.0
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240.0
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950.0
371,Jarell Eddie,Washington Wizards,8.0,SG,24.0,6-7,218.0,Virginia Tech,561716.0
370,Jared Dudley,Washington Wizards,1.0,SF,30.0,6-7,225.0,Boston College,4375000.0
374,JJ Hickson,Washington Wizards,21.0,C,27.0,6-9,242.0,North Carolina State,273038.0
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0

# Sort DataFrame with the .sort_index() Method

In [232]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv").dropna(how = "all")

In [235]:
basketball.sort_values(["Number", "Name", "Team"], inplace = True)

In [237]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0

In [239]:
basketball.sort_index() # ascending and inplace

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

# Rank Values with the .rank() Method

In [240]:
basketball = pd.read_csv("D:\python\Data Analysis with Python\#Udemy\Pandas\enba.csv").dropna(how = "all")

In [241]:
basketball["Salary"] = basketball["Salary"].fillna(0).astype("int")

In [242]:
basketball.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000

In [246]:
basketball["Salary Rank"] = basketball["Salary"].rank(ascending = False).astype("int")

In [247]:
basketball.sort_values("Salary Rank")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000,1
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500,2
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000,3
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364,4
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730,5
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695,6
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622,7
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064,8
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000,9
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000,11
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000,11
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000,11
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000,11
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,NaN,19688000,14
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726,15
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659,16
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106,17
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218,18
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501,19
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500,22
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500,22
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500,22
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500,22
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500,22
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000,25
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950,26
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950,26
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438,28
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217,29
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031,30
...,...,...,...,...,...,...,...,...,...,...
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750,428
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177,429
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888,430
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744,431
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192,432
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600,434
303,Kevin Martin,San Antonio Spurs,23.0,SG,33.0,6-7,199.0,Western Carolina,200600,434
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600,434
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455,436
282,Bryce Dejean-Jones,New Orleans Pelicans,31.0,SG,23.0,6-6,203.0,Iowa State,169883,437
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406,438
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215,439
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444,440
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444,440
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196,442
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397,443
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722,444
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722,444
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888,446
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,0,452
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,0,452
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,0,452
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,0,452
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,0,452
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0,452
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,0,452
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,0,452
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,0,452
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,0,452

---------------------------------------------------------------------------